# Generated by Django 6.0.2 on 2026-02-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('guest_type', models.CharField(choices=[('STN', 'Standard'), ('CRW', 'Crew'), ('VIP', 'VIP'), ('ART', 'Artist')], default='STN', max_length=3)),
                ('current_status', models.CharField(choices=[('REG', 'Registered'), ('CHK', 'Checked_in'), ('ENT', 'Entered'), ('EXT', 'Exited'), ('CAN', 'Cancelled')], default='REG', max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrants.event')),
            ],
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REG', 'Registered'), ('CHK', 'Checked_in'), ('ENT', 'Entered'), ('EXT', 'Exited'), ('CAN', 'Cancelled')], default='REG', max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrants.registrant')),
            ],
        ),
    ]
