# Generated by Django 6.0.2 on 2026-02-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0002_registrant_statuschange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuschange',
            old_name='date',
            new_name='date_time',
        ),
    ]
