# Generated by Django 6.0.2 on 2026-02-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0003_rename_date_statuschange_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='registrant',
            name='company_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registrants.company'),
        ),
    ]
