# Generated by Django 6.0.2 on 2026-03-03 19:34

from django.db import migrations


def update_company_fk(apps, schema_editor):
    registrant_model = apps.get_model("registrants", 'Registrant')
    company = apps.get_model("registrants", 'Company')
    
    all_registrants = registrant_model.objects.all()
    
    for registrant in all_registrants:
        company, _ = company.objects.get_or_create(name=registrant.company)
        registrant.company_fk = company
        registrant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0004_company_registrant_company_fk'),
    ]

    operations = [
      migrations.RunPython(update_company_fk)
    ]
