# Generated by Django 6.0.2 on 2026-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0005_auto_20260303_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='name',
        ),
        migrations.AlterField(
            model_name='registrant',
            name='guest_type',
            field=models.CharField(choices=[('STN', 'Standard')], default='STN', max_length=3),
        ),
    ]
