# Generated by Django 6.0.2 on 2026-03-06 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0006_remove_registrant_name_alter_registrant_guest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='company',
        ),
        migrations.AlterField(
            model_name='registrant',
            name='company_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='registrants.company'),
            preserve_default=False,
        ),
    ]
