# Generated by Django 6.0.2 on 2026-03-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0007_remove_registrant_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='name',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
