# Generated by Django 6.0.2 on 2026-03-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0008_registrant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
